language: java
jdk:
  - oraclejdk8
sudo: false
services:
  - postgresql
script:
  - mvn clean integration-test -P full
deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
  app:
    master: habiteria-api
notifications:
  slack: netcracker-2017-team:Ofl5gqjMXYz2h1VW4595QjhA