language: java
jdk:
 - oraclejdk8
sudo: false
notifications:
 slack: $SLACK_NOTIFICATIONS
  template:
   - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}) : %{message}"
   - "Build details: %{build_url}"
services:
 - postgresql
before_script:
 - psql -c "CREATE DATABASE test_db;" -U postgres
script:
 - mvn clean integration-test
deploy:
 provider: heroku
 api-key:
  secure: $HEROKU_API_KEY
 app:
  master: netcracker-2017-project
  dev: netcracker-2017-project-dev