spring:
  jpa:
    database: postgresql
    hibernate.ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driverClassName: ${JDBC_DRIVER_CLASS_NAME} # net.sf.log4jdbc.DriverSpy / org.postgresql.Driver
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}